---
title: "**Daily Economic Data Report**"
author: |
        | Giorgi Nikolaishvili
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly  
    includes:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = F)
```

```{r include=FALSE}
# Load packages 
library(pacman) 
p_load(dplyr, ggplot2)
library(fredr)
# Set FRED API key 
fredr_set_key("cbd3662cc6a06560acacf323fe5ae37a")
```

## Daily Series

```{r EFFR, echo=FALSE}
data_effr <- fredr(
          series_id = "EFFR",
          observation_start = as.Date(Sys.Date() - 100),
          observation_end = as.Date(Sys.Date())
        )
data_sofr <- fredr(
          series_id = "SOFR",
          observation_start = as.Date(Sys.Date() - 100),
          observation_end = as.Date(Sys.Date())
        )
data_obfr <- fredr(
          series_id = "OBFR",
          observation_start = as.Date(Sys.Date() - 100),
          observation_end = as.Date(Sys.Date())
        )
data <- rbind(data_effr, data_sofr)
data <- rbind(data, data_obfr)

ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1, alpha = 0.8) +
  labs(x = "Date", y = "Percent", color = "Series", title = "Overnight Bank Lending Rates") + 
  theme_minimal() 
```

```{r treasury, echo=FALSE}
series = c("DGS1", "DGS2", "DGS3", "DGS10", "DGS20", "DGS30")
data_1yr <- fredr(
              series_id = series[1],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data_2yr <- fredr(
              series_id = series[2],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data_3yr <- fredr(
              series_id = series[3],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data_10yr <- fredr(
              series_id = series[4],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data_20yr <- fredr(
              series_id = series[5],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data_30yr <- fredr(
              series_id = series[6],
              observation_start = as.Date(Sys.Date() - 100),
              observation_end = as.Date(Sys.Date())
            )
data <- rbind(data_1yr, data_2yr, data_3yr, data_10yr, data_20yr, data_30yr)

ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", y = "Percent", color = "Constant Maturity", title = "Market Yield on U.S. Treasury Securities ") + 
  theme_minimal() +
  scale_color_discrete(limits = series)
```

```{r SP500, echo = FALSE}
data <- fredr(
          series_id = "SP500",
          observation_start = as.Date(Sys.Date() - 100),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Index", 
       color = "Series", 
       title = "S&P 500") + 
  theme_minimal() 
```

## Weekly Series 

```{r WEI, echo=FALSE}
data <- fredr(
          series_id = "WEI",
          observation_start = as.Date(Sys.Date() - 7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", y = "Index", color = "Series", title = "Weekly Economic Index (Lewis-Mertens-Stock)") + 
  theme_minimal() 
```

## Monthly Series

```{r case-shiller, echo = FALSE}
data <- fredr(
          series_id = "CSUSHPISA",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Index", 
       color = "Series", 
       title = "Case-Shiller U.S. National Home Price Index (Seasonally Adj.)") + 
  theme_minimal() 
```

```{r moneystock, echo=FALSE}
data_m1 <- fredr(
          series_id = "WM1NS",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        ) %>% 
  mutate(series_id = "M1")
data_m2 <- fredr(
          series_id = "WM2NS",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        ) %>% 
  mutate(series_id = "M2") %>%
  mutate(value = value - data_m1$value)
data <- rbind(data_m2, data_m1)

ggplot(data, aes(x = date, y = value/1000, fill = series_id) ) +
  geom_area(position = position_stack(reverse = TRUE)) +
  labs(x = "Date", 
       y = "Trillions of Dollars", 
       fill = "Series", 
       title = "Money Supply") + 
  theme_minimal() 
```

```{r BBKMGDP, echo=FALSE}
data <- fredr(
          series_id = "BBKMGDP",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Annualized Percent Change from Preceding Period", 
       color = "Series", 
       title = "Brave-Butters-Kelley (US) Real Gross Domestic Product (Seasonally Adjusted)") + 
  theme_minimal() 
```

```{r IGREA, echo=FALSE}
data <- fredr(
          series_id = "IGREA",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Index", 
       color = "Series", 
       title = "Index of Global Real Economic Activity") + 
  theme_minimal() 
```

```{r HQMCB, echo=FALSE}
data_2yr <- fredr(
              series_id = "HQMCB2YR",
              observation_start = as.Date(Sys.Date() - 4*7*50),
              observation_end = as.Date(Sys.Date())
            )
data_3yr <- fredr(
              series_id = "HQMCB3YR",
              observation_start = as.Date(Sys.Date() - 4*7*50),
              observation_end = as.Date(Sys.Date())
            )
data_10yr <- fredr(
              series_id = "HQMCB10YR",
              observation_start = as.Date(Sys.Date() - 4*7*50),
              observation_end = as.Date(Sys.Date())
            )
data_15yr <- fredr(
              series_id = "HQMCB15YR",
              observation_start = as.Date(Sys.Date() - 4*7*50),
              observation_end = as.Date(Sys.Date())
            )
data_25yr <- fredr(
              series_id = "HQMCB25YR",
              observation_start = as.Date(Sys.Date() - 4*7*50),
              observation_end = as.Date(Sys.Date())
            )
data <- rbind(data_2yr, data_3yr, data_10yr, data_15yr, data_25yr)

ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", y = "Percent", color = "Series", title = "High Quality Market (HQM) Corporate Bond Spot Rate") + 
  theme_minimal() 
```

```{r EMVOVERALLEMV, echo=FALSE}
data <- fredr(
          series_id = "EMVOVERALLEMV",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Index", 
       color = "Series", 
       title = "Equity Market Volatility Tracker: Overall") + 
  theme_minimal() 
```

```{r EXPINF, echo=FALSE}
data_2yr <- fredr(
          series_id = "EXPINF2YR",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
data_5yr <- fredr(
          series_id = "EXPINF5YR",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
data_10yr <- fredr(
          series_id = "EXPINF10YR",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
data_20yr <- fredr(
          series_id = "EXPINF20YR",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
data <- rbind(data_2yr, data_5yr, data_10yr, data_20yr)

ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Percent", 
       color = "Series", 
       title = "Expected Inflation") + 
  theme_minimal() 
```

```{r ATLSBUSRGEP, echo=FALSE}
data <- fredr(
          series_id = "ATLSBUSRGEP",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Percent", 
       color = "Series", 
       title = "Business Expectations: Sales Revenue Growth") + 
  theme_minimal() 
```

```{r ATLSBUEGEP, echo=FALSE}
data <- fredr(
          series_id = "ATLSBUEGEP",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Percent", 
       color = "Series", 
       title = "Business Expectations: Employment Growth") + 
  theme_minimal() 
```

```{r H8B1023NCBCMG, echo=FALSE}
data <- fredr(
          series_id = "H8B1023NCBCMG",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Percentage Change at Annual Rate", 
       color = "Series", 
       title = "Commercial and Industrial Loans, All Commercial Banks") + 
  theme_minimal() 
```

```{r H8B1247NCBCMG, echo=FALSE}
data <- fredr(
          series_id = "H8B1247NCBCMG",
          observation_start = as.Date(Sys.Date() - 4*7*50),
          observation_end = as.Date(Sys.Date())
        )
ggplot(data, aes(x = date, y = value, color = series_id) ) +
  geom_line(size = 1) +
  labs(x = "Date", 
       y = "Percentage Change at Annual Rate", 
       color = "Series", 
       title = "Consumer Loans: Credit Cards and Other Revolving Plans, All Commercial Banks") + 
  theme_minimal() 
```

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
