on:
  schedule:
    - cron: "0 12 * * *"

name: Merge main branch to gh-pages

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main to pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ github.token }}
