on:
  schedule:
    - cron: "*/10 * * * *"
    
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: path/to/my_doc.Rmd
	  output_format: pdf_document
