on:
  schedule:
    - cron: "0 8 * * *"

name: Render Report

jobs:
  render:
    name: Render Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          #extra-packages: |
            #any::ggplot2
          needs: |
            rmarkdown 
            pacman
            fredr
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","pacman", "fredr"))'
      - name: Render rmd
        run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-user
          git add --all
          git commit -am "Update report"
          git push origin main
