on:
  schedule:
    - cron: "0 8 * * *"

name: Render Report

jobs:
  render:
    name: Render Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","pacman")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("report.Rmd")'
      - name: Commit results
        run: |
          git commit report.md -m 'Re-build report.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
